language: java

# Use container-based infrastructure to allow caching (for ccache).
sudo: false 

git:
  # Travis CI tries to clone submodules for us, but we don't want all
  # the submodules.
  submodules: false

matrix:
  include:
    - os: osx

addons:
  # To avoid an interactive prompt when uploading binaries to sourceforge.
  ssh_known_hosts: frs.sourceforge.net

# env:
#   global:

before_install:
  - BASE_DIR=$(pwd)
  - SWIG_DIR=$BASE_DIR/swig
  - SWIG_VER=2.0.8
  # Install dependencies.
  # TODO - brew update
  # TODO - brew install doxygen
  # TODO - brew cask install netbeans
  # TODO # Force some cleanup of homebrew cache so we do not exceed availabe disk space
  # TODO - brew cleanup
  # TODO - rm -rf "`brew cache`"

  # TODO - mkdir $BASE_DIR/swig-source && cd $BASE_DIR/swig-source
  # TODO - wget https://github.com/swig/swig/archive/rel-$SWIG_VER.tar.gz
  # TODO - tar xzf rel-$SWIG_VER.tar.gz && cd swig-rel-$SWIG_VER
  # TODO - sh autogen.sh
  # TODO - ./configure --prefix=$SWIG_DIR --disable-ccache
  # TODO - make
  # TODO - make -j8 install

script:
    # TODO - travis_wait 80 sh build_on_mac.sh -b $BASE_DIR -v $SWIG_VER -d $SWIG_DIR
  - echo 'TODO'

before_deploy:
  ## Set up ssh for sourceforge.
  # Decrypt the private key stored in the repository to the tmp dir.
  - openssl aes-256-cbc -K $encrypted_d246489684fa_key -iv $encrypted_d246489684fa_iv -in .deploy_myosin_sourceforge_rsa.enc -out /tmp/.deploy_myosin_sourceforge_rsa -d
  # Start the ssh agent.
  - eval "$(ssh-agent -s)"
  # Register this private key with this client (the travis machine).
  - chmod 600 /tmp/deploy_myosin_sourceforge_rsa
  - ssh-add /tmp/deploy_myosin_sourceforge_rsa
  - cat 'hello cat' > testing.txt # TODO

deploy:
  # Uploads to sourceforge.net/projects/myosin
  # See https://docs.travis-ci.com/user/deployment/custom/
  # '--archive' preserves symlinks.
  provider: script
  skip_cleanup: true
  script: rsync --archive --compress --verbose testing.txt opensim-bot@frs.sourceforge.net:/home/frs/project/myosin/opensim-build-releases
  on:
    all_branches: true

# Process for securely uploading files to Sourceforge, taken from
# https://oncletom.io/2016/travis-ssh-deploy/:
#
# Contact chrisdembia if you need the login information for opensim-bot at
# sourceforge, to manage myosin.sourceforge.net.
#
# You must install the travis command-line tool: `gem install travis`
# Locally, from the root of the repository:
# Create a 4096-bit RSA key with comment, private key 
# $ ssh-keygen -t rsa -b 4096 -C 'opensim-bot@sourceforge.net' -f .deploy_myosin_sourceforge_rsa
# When prompted for a passphrase, just hit enter (twice).
# Encrypt the private key, add decryption code to .travis.yml. First make a
# backup copy of .travis.yml.
# $ travis encrypt-file Installer/.deploy_myosin_sourceforge_rsa --add
# Manually edit the .travis.yml file to clean up the added lines and restore
# comments to the file; put the decryption in the before_deploy step.
# Remove the unencrypted private key. DO NOT commmit the unencrypted private
# key.
# $ rm -f .deploy_myosin_sourceforge_rsa
# Manually, log into the sourceforge website (user opensim-bot) and add the
# public key (contents of .deploy_myosin_sourceforge_rsa.pub) in
# Account Settings > SSH Settings.
# Now you can delete the public key file from your local machine.
# Commit the encrypted private key and the changes to .travis.yml.
# $ git add .travis.yml .deploy_myosin_sourceforge_rsa.enc
