language: java

git:
  # Travis CI tries to clone submodules for us, but we don't want all
  # the submodules.
  submodules: false

addons:
  # To avoid an interactive prompt when uploading binaries to sourceforge.
  ssh_known_hosts: frs.sourceforge.net

stages:
  - name: opensim-core-dep
    if: branch = SKIP_FOR_NOW_TODO
  - opensim-core
  - opensim-gui
  
jobs:
  include:
    - stage: opensim-core-dep
      os: osx
      addons:
        # To avoid an interactive prompt when uploading binaries to sourceforge.
        ssh_known_hosts: frs.sourceforge.net
      script:
        # - brew update
        # - brew install doxygen
        # - brew cleanup
        - travis_wait 80 sh build_on_mac.sh -s 1
      before_deploy:
        - cd $TRAVIS_BUILD_DIR
        - OPENSIM_CORE_GIT_TAG="$(xmllint --xpath "//info/opensim_core_git_tag/text()" git_tags.xml)"
        - echo $OPENSIM_CORE_GIT_TAG
        - zip --symlinks --recurse-paths --quiet opensim-core-dep-$OPENSIM_CORE_GIT_TAG.zip opensim-core-dep-install
        - ls
      deploy:
        provider: script
        skip_cleanup: true
        script: bash upload_to_sourceforge.sh opensim-core-dep-$OPENSIM_CORE_GIT_TAG.zip
        on:
          all_branches: true
    - stage: opensim-core
      os: osx
      addons:
        # To avoid an interactive prompt when uploading binaries to sourceforge.
        ssh_known_hosts: frs.sourceforge.net
      script:
        - brew update
        - brew install doxygen
        - brew cleanup
        - BASE_DIR=$(pwd)
        - BTYPE=Release
        - OSX_TARGET=10.10
        - SWIG_VER=3.0.8
        - SWIG_DIR=$BASE_DIR/swig
        - OPENSIM_CORE_SOURCE_DIR="$BASE_DIR/opensim-core"
        - OPENSIM_CORE_BUILD_DIR="$BASE_DIR/opensim-core-build"
        - OPENSIM_CORE_INSTALL_DIR="$BASE_DIR/opensim-core-install"
        - OPENSIM_CORE_DEP_SOURCE_DIR="$OPENSIM_CORE_SOURCE_DIR/dependencies"
        - OPENSIM_CORE_DEP_BUILD_DIR="$BASE_DIR/opensim-core-dep-build"
        - OPENSIM_CORE_DEP_INSTALL_DIR="$BASE_DIR/opensim-core-dep-install"
        - OPENSIM_GUI_SOURCE_DIR="$BASE_DIR/opensim-gui"
        - OPENSIM_GUI_BUILD_DIR="$BASE_DIR/opensim-gui-build"
        - OPENSIM_CORE_GIT_TAG="$(xmllint --xpath "//info/opensim_core_git_tag/text()" git_tags.xml)"
        - echo $OPENSIM_CORE_GIT_TAG
        - wget https://prdownloads.sourceforge.net/myosin/opensim-build-releases/mac/opensim-core-dep-$OPENSIM_CORE_GIT_TAG.zip
        - ls
        - unzip -q opensim-core-dep-$OPENSIM_CORE_GIT_TAG.zip
        - ls

        ## Install SWIG.
        - mkdir $BASE_DIR/swig-source && cd $BASE_DIR/swig-source
        - wget --quiet https://github.com/swig/swig/archive/rel-$SWIG_VER.tar.gz
        - tar xzf rel-$SWIG_VER.tar.gz && cd swig-rel-$SWIG_VER
        - sh autogen.sh
        - ./configure --prefix=$SWIG_DIR --disable-ccache
        - make V=0
        - make -j8 install V=0

        ## Obtain opensim-core source code.
        - OPENSIM_CORE_ZIP="$OPENSIM_CORE_GIT_TAG.zip"
        - wget --quiet https://github.com/opensim-org/opensim-core/archive/$OPENSIM_CORE_ZIP
        - unzip -q $OPENSIM_CORE_ZIP
        - mv opensim-core-$OPENSIM_CORE_GIT_TAG $OPENSIM_CORE_SOURCE_DIR

        # Configure and build opensim-core.
        - mkdir $OPENSIM_CORE_BUILD_DIR && cd $OPENSIM_CORE_BUILD_DIR
        ## Store CMake arguments in bash array.
        # https://stackoverflow.com/questions/1951506/add-a-new-element-to-an-array-without-specifying-the-index-in-bash
        - OSIM_CMAKE_ARGS=($OPENSIM_CORE_SOURCE_DIR -DCMAKE_INSTALL_PREFIX=$OPENSIM_CORE_INSTALL_DIR -DCMAKE_BUILD_TYPE=$BTYPE)
        - 
        # The deployed binaries are used by the GUI, which requires the non-FHS
        # layout.
        - OSIM_CMAKE_ARGS+=(-DOPENSIM_INSTALL_UNIX_FHS=OFF)
        - 
        # The minimum macOS/OSX version we support.
        - OSIM_CMAKE_ARGS+=(-DCMAKE_OSX_DEPLOYMENT_TARGET=$OSX_TARGET)
        - 
        # Dependencies.
        - OSIM_CMAKE_ARGS+=(-DOPENSIM_DEPENDENCIES_DIR=$OPENSIM_CORE_DEP_INSTALL_DIR -DWITH_BTK:BOOL=ON)
        - 
        # Bindings.
        - OSIM_CMAKE_ARGS+=(-DBUILD_PYTHON_WRAPPING=ON -DBUILD_JAVA_WRAPPING=ON -DSWIG_EXECUTABLE=$SWIG_DIR/bin/swig)
        # On Mac, use system python instead of Homebrew python.
        - OSIM_CMAKE_ARGS+=(-DPYTHON_EXECUTABLE=/usr/bin/python)
        - 
        # Doxygen.
        - OSIM_CMAKE_ARGS+=(-DOPENSIM_DOXYGEN_USE_MATHJAX=ON -DOPENSIM_SIMBODY_DOXYGEN_LOCATION="https://simbody.github.io/simbody-3.6-doxygen/api/index.html")
        - 
        - OSIM_CMAKE_ARGS+=(-DBUILD_TESTING=OFF)
        # Reduce verbosity of build log.
        - OSIM_CMAKE_ARGS+=(-DCMAKE_INSTALL_MESSAGE="NEVER")
        - printf '%s\n' "${OSIM_CMAKE_ARGS[@]}"
        - cmake "${OSIM_CMAKE_ARGS[@]}"
        - 
        - make doxygen
        - make -j4 install
        # TODO - travis_wait 80 sh build_on_mac.sh -s 2
      before_deploy:
        - zip --symlinks --recurse-paths --quiet opensim-core-$OPENSIM_CORE_GIT_TAG.zip opensim-core-install
      deploy:
        provider: script
        skip_cleanup: true
        script: bash upload_to_sourceforge.sh opensim-core-$OPENSIM_CORE_GIT_TAG.zip
        on:
          all_branches: true
    - stage: opensim-gui
      os: osx
      addons:
        # To avoid an interactive prompt when uploading binaries to sourceforge.
        ssh_known_hosts: frs.sourceforge.net
      script:
        - brew update
        - brew cask install netbeans
        - brew cleanup
        - wget https://prdownloads.sourceforge.net/myosin/opensim-build-releases/mac/opensim-core-$OPENSIM_CORE_GIT_TAG.zip
        - ls
        - unzip -q opensim-core-$OPENSIM_CORE_GIT_TAG.zip
        - ls
        - travis_wait 80 sh build_on_mac.sh -s 3
      before_deploy:
        - cd $TRAVIS_BUILD_DIR/opensim-gui-build
        - GUIVERSION=`cmake -L . | grep OPENSIMGUI_BUILD_VERSION | cut -d "=" -f2`
        - echo $GUIVERSION
        - cd $TRAVIS_BUILD_DIR
      deploy:
        provider: script
        skip_cleanup: true
        script: bash upload_to_sourceforge.sh $TRAVIS_BUILD_DIR/opensim-gui/Gui/opensim/dist/OpenSim-$GUIVERSION.pkg 
        on:
          all_branches: true

# Process for securely uploading files to Sourceforge, taken from
# https://oncletom.io/2016/travis-ssh-deploy/:
#
# Contact chrisdembia if you need the login information for opensim-bot at
# sourceforge, to manage myosin.sourceforge.net.
#
# You must install the travis command-line tool: `gem install travis`
# Locally, from the root of the repository:
# Create a 4096-bit RSA key with comment, private key 
# $ ssh-keygen -t rsa -b 4096 -C 'opensim-bot@sourceforge.net' -f .deploy_myosin_sourceforge_rsa
# When prompted for a passphrase, just hit enter (twice).
# Encrypt the private key, add decryption code to .travis.yml. First make a
# backup copy of .travis.yml.
# $ travis encrypt-file Installer/.deploy_myosin_sourceforge_rsa --add
# Manually edit the .travis.yml file to clean up the added lines and restore
# comments to the file; put the decryption in the before_deploy step.
# Remove the unencrypted private key. DO NOT commmit the unencrypted private
# key.
# $ rm -f .deploy_myosin_sourceforge_rsa
# Manually, log into the sourceforge website (user opensim-bot) and add the
# public key (contents of .deploy_myosin_sourceforge_rsa.pub) in
# Account Settings > SSH Settings.
# Now you can delete the public key file from your local machine.
# Commit the encrypted private key and the changes to .travis.yml.
# $ git add .travis.yml .deploy_myosin_sourceforge_rsa.enc
